// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxjdrqmuxbkecbozyoln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54amRycW11eGJrZWNib3p5b2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5ODMxNzIsImV4cCI6MjA1NjU1OTE3Mn0.Qu4djae010xLXGbymtKssHT1IU2t9NBCOwppf5H0f8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);